apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: task-pv-storage
      mountPath: /data/redis
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim