apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce           # Le volume peut être monté en Ecriture et Lecture par un seul noeud à la fois
  hostPath:
    path: "/data/pv0001/"